# -*- coding: utf-8 -*-
"""documentos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZ-ceUa2C4fAzbGzEnrBd7sbPiMXhWTU
"""

import pandas as pd
from datetime import datetime
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Inches
import os
doc = DocxTemplate("jaziel.docx")
fecha = datetime.today().strftime("%d %b, %Y")
try:
    df = pd.read_csv('data.csv')
except FileNotFoundError:
    print("Error: No se pudo encontrar el archivo CSV 'data.csv'. Verifica la ruta.")
    exit()
directorio_imagenes = "/content/imgenes/"
nombre_imagen = "imagen.png"
ruta_imagen = os.path.join(directorio_imagenes, nombre_imagen)
imagen = InlineImage(doc, ruta_imagen, width=Inches(1))
for index, fila in df.iterrows():
    my_context = {
        'fecha': fecha,
        'imagen': imagen
    }
    context = {
        'nombre': fila['nombre'],
        'matricula': fila['matricula'],
        'correo': fila['correo'],
        'papd': fila['papd'],
        'tda': fila['tda'],
        'english2': fila['english2'],
        'amp': fila['amp'],
        'aln': fila['aln'],
    }

    context.update(my_context)
    doc.render(context)
    doc.save(f"doc_generado_{index}.docx")