# -*- coding: utf-8 -*-
"""documentos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZ-ceUa2C4fAzbGzEnrBd7sbPiMXhWTU
"""

!pip install docxtpl

from datetime import datetime

def current_date_format(date):
    months = ("Enero", "Febrero", "Marzo", "Abri", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
    day = date.day
    month = months[date.month - 1]
    year = date.year
    messsage = "{} de {} del {} ".format(day, month, year)

    return messsage

now = datetime.now()
print(current_date_format(now))

import pandas as pd
from datetime import datetime
from docxtpl import DocxTemplate, InlineImage
from docx.shared import Inches
import os
doc = DocxTemplate("jaziel.docx")
try:
    df = pd.read_csv('data.csv')
except FileNotFoundError:
    print("Error: No se pudo encontrar el archivo CSV 'data.csv'. Verifica la ruta.")
    exit()
directorio_imagenes = "/content/imgenes/"
nombre_imagen = "imagen.png"
ruta_imagen = os.path.join(directorio_imagenes, nombre_imagen)
imagen = InlineImage(doc, ruta_imagen, width=Inches(1))
for index, fila in df.iterrows():
    my_context = {
        'fecha': current_date_format(now),
        'imagen': imagen
    }
    context = {
        'nombre': fila['nombre'],
        'matricula': fila['matricula'],
        'correo': fila['correo'],
        'papd': fila['papd'],
        'tda': fila['tda'],
        'english2': fila['english2'],
        'amp': fila['amp'],
        'aln': fila['aln'],
    }

    context.update(my_context)
    doc.render(context)
    doc.save(f"doc_generado_{index}.docx")